name: Build and Deploy to Server
on:
  release:
    types:
      - created
  push:
    branches: [ main ]      

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [10.x, 12.x, 14.x]
    steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: npm ci
#     - run: npm run build --if-present
    
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
           rm -rf code/folder
           
    - name: parent working directory
      run: pwd
           
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: /home/runner/work/ssh-deploy/ssh-deploy/folder
        remote: code
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
