name: Build and Deploy to Server
on:
  release:
    types:
      - created
  push:
    branches: [ main ]      

jobs:
  setup-build-publish-deploy:
  - name: executing remote ssh commands using password
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}
      port: ${{ secrets.PORT }}
      script: ls -al
